export type Country = {
  code: string;
  dialCode: string;
  names: {
    cz: string;
    en: string;
  };
};

export const COUNTRIES: Country[] = [
  { code: "AC", dialCode: "+247", names: { cz: "Ascension", en: "Ascension Island" } },
  { code: "AD", dialCode: "+376", names: { cz: "Andorra", en: "Andorra" } },
  { code: "AE", dialCode: "+971", names: { cz: "Spojené arabské emiráty", en: "United Arab Emirates" } },
  { code: "AF", dialCode: "+93", names: { cz: "Afghánistán", en: "Afghanistan" } },
  { code: "AG", dialCode: "+1", names: { cz: "Antigua a Barbuda", en: "Antigua & Barbuda" } },
  { code: "AI", dialCode: "+1", names: { cz: "Anguilla", en: "Anguilla" } },
  { code: "AL", dialCode: "+355", names: { cz: "Albánie", en: "Albania" } },
  { code: "AM", dialCode: "+374", names: { cz: "Arménie", en: "Armenia" } },
  { code: "AO", dialCode: "+244", names: { cz: "Angola", en: "Angola" } },
  { code: "AR", dialCode: "+54", names: { cz: "Argentina", en: "Argentina" } },
  { code: "AS", dialCode: "+1", names: { cz: "Americká Samoa", en: "American Samoa" } },
  { code: "AT", dialCode: "+43", names: { cz: "Rakousko", en: "Austria" } },
  { code: "AU", dialCode: "+61", names: { cz: "Austrálie", en: "Australia" } },
  { code: "AW", dialCode: "+297", names: { cz: "Aruba", en: "Aruba" } },
  { code: "AX", dialCode: "+358", names: { cz: "Ålandy", en: "Åland Islands" } },
  { code: "AZ", dialCode: "+994", names: { cz: "Ázerbájdžán", en: "Azerbaijan" } },
  { code: "BA", dialCode: "+387", names: { cz: "Bosna a Hercegovina", en: "Bosnia & Herzegovina" } },
  { code: "BB", dialCode: "+1", names: { cz: "Barbados", en: "Barbados" } },
  { code: "BD", dialCode: "+880", names: { cz: "Bangladéš", en: "Bangladesh" } },
  { code: "BE", dialCode: "+32", names: { cz: "Belgie", en: "Belgium" } },
  { code: "BF", dialCode: "+226", names: { cz: "Burkina Faso", en: "Burkina Faso" } },
  { code: "BG", dialCode: "+359", names: { cz: "Bulharsko", en: "Bulgaria" } },
  { code: "BH", dialCode: "+973", names: { cz: "Bahrajn", en: "Bahrain" } },
  { code: "BI", dialCode: "+257", names: { cz: "Burundi", en: "Burundi" } },
  { code: "BJ", dialCode: "+229", names: { cz: "Benin", en: "Benin" } },
  { code: "BL", dialCode: "+590", names: { cz: "Svatý Bartoloměj", en: "St. Barthélemy" } },
  { code: "BM", dialCode: "+1", names: { cz: "Bermudy", en: "Bermuda" } },
  { code: "BN", dialCode: "+673", names: { cz: "Brunej", en: "Brunei" } },
  { code: "BO", dialCode: "+591", names: { cz: "Bolívie", en: "Bolivia" } },
  { code: "BQ", dialCode: "+599", names: { cz: "Karibské Nizozemsko", en: "Caribbean Netherlands" } },
  { code: "BR", dialCode: "+55", names: { cz: "Brazílie", en: "Brazil" } },
  { code: "BS", dialCode: "+1", names: { cz: "Bahamy", en: "Bahamas" } },
  { code: "BT", dialCode: "+975", names: { cz: "Bhútán", en: "Bhutan" } },
  { code: "BW", dialCode: "+267", names: { cz: "Botswana", en: "Botswana" } },
  { code: "BY", dialCode: "+375", names: { cz: "Bělorusko", en: "Belarus" } },
  { code: "BZ", dialCode: "+501", names: { cz: "Belize", en: "Belize" } },
  { code: "CA", dialCode: "+1", names: { cz: "Kanada", en: "Canada" } },
  { code: "CC", dialCode: "+61", names: { cz: "Kokosové ostrovy", en: "Cocos (Keeling) Islands" } },
  { code: "CD", dialCode: "+243", names: { cz: "Kongo – Kinshasa", en: "Congo - Kinshasa" } },
  { code: "CF", dialCode: "+236", names: { cz: "Středoafrická republika", en: "Central African Republic" } },
  { code: "CG", dialCode: "+242", names: { cz: "Kongo – Brazzaville", en: "Congo - Brazzaville" } },
  { code: "CI", dialCode: "+225", names: { cz: "Pobřeží slonoviny", en: "Côte d’Ivoire" } },
  { code: "CK", dialCode: "+682", names: { cz: "Cookovy ostrovy", en: "Cook Islands" } },
  { code: "CL", dialCode: "+56", names: { cz: "Chile", en: "Chile" } },
  { code: "CM", dialCode: "+237", names: { cz: "Kamerun", en: "Cameroon" } },
  { code: "CN", dialCode: "+86", names: { cz: "Čína", en: "China" } },
  { code: "CO", dialCode: "+57", names: { cz: "Kolumbie", en: "Colombia" } },
  { code: "CR", dialCode: "+506", names: { cz: "Kostarika", en: "Costa Rica" } },
  { code: "CU", dialCode: "+53", names: { cz: "Kuba", en: "Cuba" } },
  { code: "CV", dialCode: "+238", names: { cz: "Kapverdy", en: "Cape Verde" } },
  { code: "CW", dialCode: "+599", names: { cz: "Curaçao", en: "Curaçao" } },
  { code: "CX", dialCode: "+61", names: { cz: "Vánoční ostrov", en: "Christmas Island" } },
  { code: "CY", dialCode: "+357", names: { cz: "Kypr", en: "Cyprus" } },
  { code: "CZ", dialCode: "+420", names: { cz: "Česká republika", en: "Czech Republic" } },
  { code: "DE", dialCode: "+49", names: { cz: "Německo", en: "Germany" } },
  { code: "DJ", dialCode: "+253", names: { cz: "Džibutsko", en: "Djibouti" } },
  { code: "DK", dialCode: "+45", names: { cz: "Dánsko", en: "Denmark" } },
  { code: "DM", dialCode: "+1", names: { cz: "Dominika", en: "Dominica" } },
  { code: "DO", dialCode: "+1", names: { cz: "Dominikánská republika", en: "Dominican Republic" } },
  { code: "DZ", dialCode: "+213", names: { cz: "Alžírsko", en: "Algeria" } },
  { code: "EC", dialCode: "+593", names: { cz: "Ekvádor", en: "Ecuador" } },
  { code: "EE", dialCode: "+372", names: { cz: "Estonsko", en: "Estonia" } },
  { code: "EG", dialCode: "+20", names: { cz: "Egypt", en: "Egypt" } },
  { code: "EH", dialCode: "+212", names: { cz: "Západní Sahara", en: "Western Sahara" } },
  { code: "ER", dialCode: "+291", names: { cz: "Eritrea", en: "Eritrea" } },
  { code: "ES", dialCode: "+34", names: { cz: "Španělsko", en: "Spain" } },
  { code: "ET", dialCode: "+251", names: { cz: "Etiopie", en: "Ethiopia" } },
  { code: "FI", dialCode: "+358", names: { cz: "Finsko", en: "Finland" } },
  { code: "FJ", dialCode: "+679", names: { cz: "Fidži", en: "Fiji" } },
  { code: "FK", dialCode: "+500", names: { cz: "Falklandské ostrovy", en: "Falkland Islands" } },
  { code: "FM", dialCode: "+691", names: { cz: "Mikronésie", en: "Micronesia" } },
  { code: "FO", dialCode: "+298", names: { cz: "Faerské ostrovy", en: "Faroe Islands" } },
  { code: "FR", dialCode: "+33", names: { cz: "Francie", en: "France" } },
  { code: "GA", dialCode: "+241", names: { cz: "Gabon", en: "Gabon" } },
  { code: "GB", dialCode: "+44", names: { cz: "Spojené království", en: "United Kingdom" } },
  { code: "GD", dialCode: "+1", names: { cz: "Grenada", en: "Grenada" } },
  { code: "GE", dialCode: "+995", names: { cz: "Gruzie", en: "Georgia" } },
  { code: "GF", dialCode: "+594", names: { cz: "Francouzská Guyana", en: "French Guiana" } },
  { code: "GG", dialCode: "+44", names: { cz: "Guernsey", en: "Guernsey" } },
  { code: "GH", dialCode: "+233", names: { cz: "Ghana", en: "Ghana" } },
  { code: "GI", dialCode: "+350", names: { cz: "Gibraltar", en: "Gibraltar" } },
  { code: "GL", dialCode: "+299", names: { cz: "Grónsko", en: "Greenland" } },
  { code: "GM", dialCode: "+220", names: { cz: "Gambie", en: "Gambia" } },
  { code: "GN", dialCode: "+224", names: { cz: "Guinea", en: "Guinea" } },
  { code: "GP", dialCode: "+590", names: { cz: "Guadeloupe", en: "Guadeloupe" } },
  { code: "GQ", dialCode: "+240", names: { cz: "Rovníková Guinea", en: "Equatorial Guinea" } },
  { code: "GR", dialCode: "+30", names: { cz: "Řecko", en: "Greece" } },
  { code: "GT", dialCode: "+502", names: { cz: "Guatemala", en: "Guatemala" } },
  { code: "GU", dialCode: "+1", names: { cz: "Guam", en: "Guam" } },
  { code: "GW", dialCode: "+245", names: { cz: "Guinea-Bissau", en: "Guinea-Bissau" } },
  { code: "GY", dialCode: "+592", names: { cz: "Guyana", en: "Guyana" } },
  { code: "HK", dialCode: "+852", names: { cz: "Hongkong – ZAO Číny", en: "Hong Kong SAR China" } },
  { code: "HN", dialCode: "+504", names: { cz: "Honduras", en: "Honduras" } },
  { code: "HR", dialCode: "+385", names: { cz: "Chorvatsko", en: "Croatia" } },
  { code: "HT", dialCode: "+509", names: { cz: "Haiti", en: "Haiti" } },
  { code: "HU", dialCode: "+36", names: { cz: "Maďarsko", en: "Hungary" } },
  { code: "CH", dialCode: "+41", names: { cz: "Švýcarsko", en: "Switzerland" } },
  { code: "ID", dialCode: "+62", names: { cz: "Indonésie", en: "Indonesia" } },
  { code: "IE", dialCode: "+353", names: { cz: "Irsko", en: "Ireland" } },
  { code: "IL", dialCode: "+972", names: { cz: "Izrael", en: "Israel" } },
  { code: "IM", dialCode: "+44", names: { cz: "Ostrov Man", en: "Isle of Man" } },
  { code: "IN", dialCode: "+91", names: { cz: "Indie", en: "India" } },
  { code: "IO", dialCode: "+246", names: { cz: "Britské indickooceánské území", en: "British Indian Ocean Territory" } },
  { code: "IQ", dialCode: "+964", names: { cz: "Irák", en: "Iraq" } },
  { code: "IR", dialCode: "+98", names: { cz: "Írán", en: "Iran" } },
  { code: "IS", dialCode: "+354", names: { cz: "Island", en: "Iceland" } },
  { code: "IT", dialCode: "+39", names: { cz: "Itálie", en: "Italy" } },
  { code: "JE", dialCode: "+44", names: { cz: "Jersey", en: "Jersey" } },
  { code: "JM", dialCode: "+1", names: { cz: "Jamajka", en: "Jamaica" } },
  { code: "JO", dialCode: "+962", names: { cz: "Jordánsko", en: "Jordan" } },
  { code: "JP", dialCode: "+81", names: { cz: "Japonsko", en: "Japan" } },
  { code: "KE", dialCode: "+254", names: { cz: "Keňa", en: "Kenya" } },
  { code: "KG", dialCode: "+996", names: { cz: "Kyrgyzstán", en: "Kyrgyzstan" } },
  { code: "KH", dialCode: "+855", names: { cz: "Kambodža", en: "Cambodia" } },
  { code: "KI", dialCode: "+686", names: { cz: "Kiribati", en: "Kiribati" } },
  { code: "KM", dialCode: "+269", names: { cz: "Komory", en: "Comoros" } },
  { code: "KN", dialCode: "+1", names: { cz: "Svatý Kryštof a Nevis", en: "St. Kitts & Nevis" } },
  { code: "KP", dialCode: "+850", names: { cz: "Severní Korea", en: "North Korea" } },
  { code: "KR", dialCode: "+82", names: { cz: "Jižní Korea", en: "South Korea" } },
  { code: "KW", dialCode: "+965", names: { cz: "Kuvajt", en: "Kuwait" } },
  { code: "KY", dialCode: "+1", names: { cz: "Kajmanské ostrovy", en: "Cayman Islands" } },
  { code: "KZ", dialCode: "+7", names: { cz: "Kazachstán", en: "Kazakhstan" } },
  { code: "LA", dialCode: "+856", names: { cz: "Laos", en: "Laos" } },
  { code: "LB", dialCode: "+961", names: { cz: "Libanon", en: "Lebanon" } },
  { code: "LC", dialCode: "+1", names: { cz: "Svatá Lucie", en: "St. Lucia" } },
  { code: "LI", dialCode: "+423", names: { cz: "Lichtenštejnsko", en: "Liechtenstein" } },
  { code: "LK", dialCode: "+94", names: { cz: "Srí Lanka", en: "Sri Lanka" } },
  { code: "LR", dialCode: "+231", names: { cz: "Libérie", en: "Liberia" } },
  { code: "LS", dialCode: "+266", names: { cz: "Lesotho", en: "Lesotho" } },
  { code: "LT", dialCode: "+370", names: { cz: "Litva", en: "Lithuania" } },
  { code: "LU", dialCode: "+352", names: { cz: "Lucembursko", en: "Luxembourg" } },
  { code: "LV", dialCode: "+371", names: { cz: "Lotyšsko", en: "Latvia" } },
  { code: "LY", dialCode: "+218", names: { cz: "Libye", en: "Libya" } },
  { code: "MA", dialCode: "+212", names: { cz: "Maroko", en: "Morocco" } },
  { code: "MC", dialCode: "+377", names: { cz: "Monako", en: "Monaco" } },
  { code: "MD", dialCode: "+373", names: { cz: "Moldavsko", en: "Moldova" } },
  { code: "ME", dialCode: "+382", names: { cz: "Černá Hora", en: "Montenegro" } },
  { code: "MF", dialCode: "+590", names: { cz: "Svatý Martin (Francie)", en: "St. Martin" } },
  { code: "MG", dialCode: "+261", names: { cz: "Madagaskar", en: "Madagascar" } },
  { code: "MH", dialCode: "+692", names: { cz: "Marshallovy ostrovy", en: "Marshall Islands" } },
  { code: "MK", dialCode: "+389", names: { cz: "Severní Makedonie", en: "North Macedonia" } },
  { code: "ML", dialCode: "+223", names: { cz: "Mali", en: "Mali" } },
  { code: "MM", dialCode: "+95", names: { cz: "Myanmar (Barma)", en: "Myanmar (Burma)" } },
  { code: "MN", dialCode: "+976", names: { cz: "Mongolsko", en: "Mongolia" } },
  { code: "MO", dialCode: "+853", names: { cz: "Macao – ZAO Číny", en: "Macao SAR China" } },
  { code: "MP", dialCode: "+1", names: { cz: "Severní Mariany", en: "Northern Mariana Islands" } },
  { code: "MQ", dialCode: "+596", names: { cz: "Martinik", en: "Martinique" } },
  { code: "MR", dialCode: "+222", names: { cz: "Mauritánie", en: "Mauritania" } },
  { code: "MS", dialCode: "+1", names: { cz: "Montserrat", en: "Montserrat" } },
  { code: "MT", dialCode: "+356", names: { cz: "Malta", en: "Malta" } },
  { code: "MU", dialCode: "+230", names: { cz: "Mauricius", en: "Mauritius" } },
  { code: "MV", dialCode: "+960", names: { cz: "Maledivy", en: "Maldives" } },
  { code: "MW", dialCode: "+265", names: { cz: "Malawi", en: "Malawi" } },
  { code: "MX", dialCode: "+52", names: { cz: "Mexiko", en: "Mexico" } },
  { code: "MY", dialCode: "+60", names: { cz: "Malajsie", en: "Malaysia" } },
  { code: "MZ", dialCode: "+258", names: { cz: "Mosambik", en: "Mozambique" } },
  { code: "NA", dialCode: "+264", names: { cz: "Namibie", en: "Namibia" } },
  { code: "NC", dialCode: "+687", names: { cz: "Nová Kaledonie", en: "New Caledonia" } },
  { code: "NE", dialCode: "+227", names: { cz: "Niger", en: "Niger" } },
  { code: "NF", dialCode: "+672", names: { cz: "Norfolk", en: "Norfolk Island" } },
  { code: "NG", dialCode: "+234", names: { cz: "Nigérie", en: "Nigeria" } },
  { code: "NI", dialCode: "+505", names: { cz: "Nikaragua", en: "Nicaragua" } },
  { code: "NL", dialCode: "+31", names: { cz: "Nizozemsko", en: "Netherlands" } },
  { code: "NO", dialCode: "+47", names: { cz: "Norsko", en: "Norway" } },
  { code: "NP", dialCode: "+977", names: { cz: "Nepál", en: "Nepal" } },
  { code: "NR", dialCode: "+674", names: { cz: "Nauru", en: "Nauru" } },
  { code: "NU", dialCode: "+683", names: { cz: "Niue", en: "Niue" } },
  { code: "NZ", dialCode: "+64", names: { cz: "Nový Zéland", en: "New Zealand" } },
  { code: "OM", dialCode: "+968", names: { cz: "Omán", en: "Oman" } },
  { code: "PA", dialCode: "+507", names: { cz: "Panama", en: "Panama" } },
  { code: "PE", dialCode: "+51", names: { cz: "Peru", en: "Peru" } },
  { code: "PF", dialCode: "+689", names: { cz: "Francouzská Polynésie", en: "French Polynesia" } },
  { code: "PG", dialCode: "+675", names: { cz: "Papua-Nová Guinea", en: "Papua New Guinea" } },
  { code: "PH", dialCode: "+63", names: { cz: "Filipíny", en: "Philippines" } },
  { code: "PK", dialCode: "+92", names: { cz: "Pákistán", en: "Pakistan" } },
  { code: "PL", dialCode: "+48", names: { cz: "Polsko", en: "Poland" } },
  { code: "PM", dialCode: "+508", names: { cz: "Saint-Pierre a Miquelon", en: "St. Pierre & Miquelon" } },
  { code: "PR", dialCode: "+1", names: { cz: "Portoriko", en: "Puerto Rico" } },
  { code: "PS", dialCode: "+970", names: { cz: "Palestinská území", en: "Palestinian Territories" } },
  { code: "PT", dialCode: "+351", names: { cz: "Portugalsko", en: "Portugal" } },
  { code: "PW", dialCode: "+680", names: { cz: "Palau", en: "Palau" } },
  { code: "PY", dialCode: "+595", names: { cz: "Paraguay", en: "Paraguay" } },
  { code: "QA", dialCode: "+974", names: { cz: "Katar", en: "Qatar" } },
  { code: "RE", dialCode: "+262", names: { cz: "Réunion", en: "Réunion" } },
  { code: "RO", dialCode: "+40", names: { cz: "Rumunsko", en: "Romania" } },
  { code: "RS", dialCode: "+381", names: { cz: "Srbsko", en: "Serbia" } },
  { code: "RU", dialCode: "+7", names: { cz: "Rusko", en: "Russia" } },
  { code: "RW", dialCode: "+250", names: { cz: "Rwanda", en: "Rwanda" } },
  { code: "SA", dialCode: "+966", names: { cz: "Saúdská Arábie", en: "Saudi Arabia" } },
  { code: "SB", dialCode: "+677", names: { cz: "Šalamounovy ostrovy", en: "Solomon Islands" } },
  { code: "SC", dialCode: "+248", names: { cz: "Seychely", en: "Seychelles" } },
  { code: "SD", dialCode: "+249", names: { cz: "Súdán", en: "Sudan" } },
  { code: "SE", dialCode: "+46", names: { cz: "Švédsko", en: "Sweden" } },
  { code: "SG", dialCode: "+65", names: { cz: "Singapur", en: "Singapore" } },
  { code: "SH", dialCode: "+290", names: { cz: "Svatá Helena", en: "St. Helena" } },
  { code: "SI", dialCode: "+386", names: { cz: "Slovinsko", en: "Slovenia" } },
  { code: "SJ", dialCode: "+47", names: { cz: "Špicberky a Jan Mayen", en: "Svalbard & Jan Mayen" } },
  { code: "SK", dialCode: "+421", names: { cz: "Slovenská republika", en: "Slovakia" } },
  { code: "SL", dialCode: "+232", names: { cz: "Sierra Leone", en: "Sierra Leone" } },
  { code: "SM", dialCode: "+378", names: { cz: "San Marino", en: "San Marino" } },
  { code: "SN", dialCode: "+221", names: { cz: "Senegal", en: "Senegal" } },
  { code: "SO", dialCode: "+252", names: { cz: "Somálsko", en: "Somalia" } },
  { code: "SR", dialCode: "+597", names: { cz: "Surinam", en: "Suriname" } },
  { code: "SS", dialCode: "+211", names: { cz: "Jižní Súdán", en: "South Sudan" } },
  { code: "ST", dialCode: "+239", names: { cz: "Svatý Tomáš a Princův ostrov", en: "São Tomé & Príncipe" } },
  { code: "SV", dialCode: "+503", names: { cz: "Salvador", en: "El Salvador" } },
  { code: "SX", dialCode: "+1", names: { cz: "Svatý Martin (Nizozemsko)", en: "Sint Maarten" } },
  { code: "SY", dialCode: "+963", names: { cz: "Sýrie", en: "Syria" } },
  { code: "SZ", dialCode: "+268", names: { cz: "Svazijsko", en: "Eswatini" } },
  { code: "TC", dialCode: "+1", names: { cz: "Turks a Caicos", en: "Turks & Caicos Islands" } },
  { code: "TD", dialCode: "+235", names: { cz: "Čad", en: "Chad" } },
  { code: "TG", dialCode: "+228", names: { cz: "Togo", en: "Togo" } },
  { code: "TH", dialCode: "+66", names: { cz: "Thajsko", en: "Thailand" } },
  { code: "TJ", dialCode: "+992", names: { cz: "Tádžikistán", en: "Tajikistan" } },
  { code: "TK", dialCode: "+690", names: { cz: "Tokelau", en: "Tokelau" } },
  { code: "TL", dialCode: "+670", names: { cz: "Východní Timor", en: "Timor-Leste" } },
  { code: "TM", dialCode: "+993", names: { cz: "Turkmenistán", en: "Turkmenistan" } },
  { code: "TN", dialCode: "+216", names: { cz: "Tunisko", en: "Tunisia" } },
  { code: "TO", dialCode: "+676", names: { cz: "Tonga", en: "Tonga" } },
  { code: "TR", dialCode: "+90", names: { cz: "Turecko", en: "Turkey" } },
  { code: "TT", dialCode: "+1", names: { cz: "Trinidad a Tobago", en: "Trinidad & Tobago" } },
  { code: "TV", dialCode: "+688", names: { cz: "Tuvalu", en: "Tuvalu" } },
  { code: "TW", dialCode: "+886", names: { cz: "Tchaj-wan", en: "Taiwan" } },
  { code: "TZ", dialCode: "+255", names: { cz: "Tanzanie", en: "Tanzania" } },
  { code: "UA", dialCode: "+380", names: { cz: "Ukrajina", en: "Ukraine" } },
  { code: "UG", dialCode: "+256", names: { cz: "Uganda", en: "Uganda" } },
  { code: "US", dialCode: "+1", names: { cz: "Spojené státy", en: "United States" } },
  { code: "UY", dialCode: "+598", names: { cz: "Uruguay", en: "Uruguay" } },
  { code: "UZ", dialCode: "+998", names: { cz: "Uzbekistán", en: "Uzbekistan" } },
  { code: "VA", dialCode: "+39", names: { cz: "Vatikán", en: "Vatican City" } },
  { code: "VC", dialCode: "+1", names: { cz: "Svatý Vincenc a Grenadiny", en: "St. Vincent & Grenadines" } },
  { code: "VE", dialCode: "+58", names: { cz: "Venezuela", en: "Venezuela" } },
  { code: "VG", dialCode: "+1", names: { cz: "Britské Panenské ostrovy", en: "British Virgin Islands" } },
  { code: "VI", dialCode: "+1", names: { cz: "Americké Panenské ostrovy", en: "U.S. Virgin Islands" } },
  { code: "VN", dialCode: "+84", names: { cz: "Vietnam", en: "Vietnam" } },
  { code: "VU", dialCode: "+678", names: { cz: "Vanuatu", en: "Vanuatu" } },
  { code: "WF", dialCode: "+681", names: { cz: "Wallis a Futuna", en: "Wallis & Futuna" } },
  { code: "WS", dialCode: "+685", names: { cz: "Samoa", en: "Samoa" } },
  { code: "XK", dialCode: "+383", names: { cz: "Kosovo", en: "Kosovo" } },
  { code: "YE", dialCode: "+967", names: { cz: "Jemen", en: "Yemen" } },
  { code: "YT", dialCode: "+262", names: { cz: "Mayotte", en: "Mayotte" } },
  { code: "ZA", dialCode: "+27", names: { cz: "Jihoafrická republika", en: "South Africa" } },
  { code: "ZM", dialCode: "+260", names: { cz: "Zambie", en: "Zambia" } },
  { code: "ZW", dialCode: "+263", names: { cz: "Zimbabwe", en: "Zimbabwe" } },
];

export type LocaleKey = "cz" | "en";

export function flagEmoji(code: string) {
  return code
    .toUpperCase()
    .split("")
    .map((char) => String.fromCodePoint(127397 + char.charCodeAt(0)))
    .join("");
}

export function getCountryName(country: Country, locale: LocaleKey) {
  return country.names[locale];
}

export function sortCountries(locale: LocaleKey) {
  // "cz" is a country-style route prefix; collation needs BCP-47 "cs".
  const collationLocale = locale === "cz" ? "cs" : locale;
  return [...COUNTRIES].sort((a, b) =>
    getCountryName(a, locale).localeCompare(getCountryName(b, locale), collationLocale),
  );
}

export function getCountryByCode(code: string) {
  return COUNTRIES.find((country) => country.code === code);
}

export const DEFAULT_COUNTRY_CODE = "CZ";
